# Generated by Django 3.1 on 2020-12-23 19:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('keywords', models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('css', 'CSS'), ('html', 'HTML'), ('dj', 'Django'), ('db', 'Database')], max_length=100)),
                ('author', models.CharField(default='http://sdt-inc.github.io/', max_length=399)),
                ('title', models.CharField(max_length=200)),
                ('writer_name', models.CharField(choices=[('NH', 'Md. Nahid Hassan'), ('MN', 'Md. Mehedi Hasan')], default='Md. Nahid Hassan', max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('related_page_link', models.URLField()),
            ],
        ),
    ]
