# Generated by Django 3.1 on 2020-12-23 19:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201224_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythondb',
            name='keywords',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('css', 'CSS'), ('html', 'HTML'), ('dj', 'Django'), ('db', 'Database')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pythondb',
            name='writer_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NH', 'Md. Nahid Hassan'), ('MN', 'Md. Mehedi Hasan')], max_length=5),
        ),
    ]
