# Generated by Django 3.1.4 on 2020-12-24 18:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201224_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythondb',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
