# Generated by Django 3.1.4 on 2021-01-16 18:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='keywords',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('Django', 'Django'), ('Database', 'Database')], max_length=42),
        ),
        migrations.AlterField(
            model_name='blogdb',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('Django', 'Django'), ('Database', 'Database')], max_length=42),
        ),
        migrations.AlterField(
            model_name='pythondb',
            name='keywords',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('Django', 'Django'), ('Database', 'Database')], max_length=42),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogdb')),
            ],
        ),
    ]
