# Generated by Django 3.1.4 on 2023-07-30 03:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_blogdb_keywords_remove_blogdb_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdb',
            name='keywords',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('Django', 'Django'), ('PHP', 'PHP'), ('Others', 'Others')], default='python', max_length=44),
        ),
        migrations.AddField(
            model_name='blogdb',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('Django', 'Django'), ('PHP', 'PHP'), ('Others', 'Others')], default='python', max_length=44),
        ),
        migrations.AddField(
            model_name='blogdb',
            name='writer_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NH', 'Md. Nahid Hassan'), ('MN', 'Md. Mehedi Hasan'), ('M3C', 'Mursalin Chowdhury')], default='mahin', max_length=9),
        ),
        migrations.AddField(
            model_name='pythondb',
            name='keywords',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('Django', 'Django'), ('PHP', 'PHP'), ('Others', 'Others')], default='python', max_length=44),
        ),
        migrations.AddField(
            model_name='pythondb',
            name='writer_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NH', 'Md. Nahid Hassan'), ('MN', 'Md. Mehedi Hasan'), ('M3C', 'Mursalin Chowdhury')], default='mahin', max_length=9),
        ),
    ]
