# Generated by Django 3.1.4 on 2023-07-30 03:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230730_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='keywords',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('CSS', 'CSS'), ('HTML', 'HTML'), ('Django', 'Django'), ('PHP', 'PHP'), ('Others', 'Others')], max_length=44),
        ),
        migrations.AlterField(
            model_name='blogdb',
            name='writer_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NH', 'Md. Nahid Hassan'), ('MN', 'Md. Mehedi Hasan'), ('M3C', 'Mursalin Chowdhury')], max_length=9),
        ),
    ]
